import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/ThemeProvider';
import { Header } from '@/components/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

import { AuthProvider } from '@/context/AuthContext';
import AuthGuard from '@/components/AuthGuard';
import Footer from '@/components/Footer';

import RecaptchaProvider from '@/providers/RecaptchaProvider';

export const metadata: Metadata = {
  title: {
    template: '%s | Interview Recorder',
    default: 'Interview Recorder - 면접 질문 기록 및 연습',
  },
  description:
    '면접 질문을 체계적으로 기록하고, 답변을 연습하여 합격 확률을 높이세요.',
  keywords: [
    '면접',
    '면접 질문',
    '면접 연습',
    '취업',
    '이직',
    '인터뷰',
    '커리어',
  ],
  authors: [{ name: 'Interview Recorder Team' }],
  openGraph: {
    title: 'Interview Recorder',
    description: '당신의 면접을 완벽하게 준비하는 공간',
    url: 'https://interview-recorder.vercel.app', // Update with actual URL if known, or generic
    siteName: 'Interview Recorder',
    images: [
      {
        url: '/og-image.png', // We might need to generate this or use a default
        width: 1200,
        height: 630,
      },
    ],
    locale: 'ko_KR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Interview Recorder',
    description: '면접 질문 아카이빙 및 답변 연습 서비스',
  },
  icons: {
    icon: '/icon', // Auto-generated by icon.tsx
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RecaptchaProvider>
          <ThemeProvider>
            <AuthProvider>
              <AuthGuard>
                <Header />
                <div
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    minHeight: '100vh',
                  }}
                >
                  <div style={{ flex: 1 }}>{children}</div>
                  <Footer />
                </div>
              </AuthGuard>
            </AuthProvider>
          </ThemeProvider>
        </RecaptchaProvider>
      </body>
    </html>
  );
}
